### ISSUE TITLE
PROTOTIPO DE REALIDAD AUMENTADA

### ISSUE THREAD

**Issue by Eva155** [SistemasTecTlaxiaco/diseno-de-prototipo-de-realidad-aumentada-equipo_prestadores-de-servicios#2]
[PROTOTIPO DE REALIDAD AUMENTADA.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-prototipo-de-realidad-aumentada-equipo_prestadores-de-servicios/files/8122080/PROTOTIPO.DE.REALIDAD.AUMENTADA.pdf)

**Comment by IvanMc98** [comment]
El reporte de la practica contiene información clara acerca del objetivo del proyecto.
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
